- name: Remove old cluster
  command:
    kubeadm reset --force
  tags:
  - removeCluster
  register: kubeadm_reset

- name: Initialize k8s cluster
  command:
    kubeadm init
  tags:
  - initCluster
  register: kubeadm_init

- name: Create .kube dir
  file:
    path: ~/.kube
    state: directory
  tags:
  - createKubeDir

- name: Link admin.conf in ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
  tags:
  - linkKubeConfigAtUserDir

- name: Configure Weavenet pod network
  #k8s:
  #  state: present
  #  definition: {{ default_url_weavenet}}
  #  namespace: default
  shell: kubectl apply -f {{ default_url_weavenet}}
  tags:
  - configWeavenet
  register: weavenet_result

- name: Save token to workers addition on cluster
  shell: kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
  register: k8s_token

- name: CA Hash
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: k8s_master_ca_hash

- name: Add token and hash into a dummy host
  add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ k8s_token.stdout }}"
    hash: "{{ k8s_master_ca_hash.stdout }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - O token eh {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER - O hash eh {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"